### ISSUE TITLE
ProvidesEventsForm should extend ZfcBase\EventManager\EventProvider

### ISSUE THREAD

**Issue by texdc** [ZF-Commons/ZfcBase#56]
Why is code duplicated?  Is there a valid reason?

**Comment by adamlundrigan** [comment]
@Danielss89 this can be closed

**Comment by texdc** [comment]
[EventManagerAwareTrait](https://github.com/zendframework/zf2/blob/master/library/Zend/EventManager/EventManagerAwareTrait.php) ... Beuler?

**Comment by adamlundrigan** [comment]
ZfcUser 1.x and ZfcBase 0.x currently support PHP 5.3, which doesn't have traits

**Comment by texdc** [comment]
Seems a little out of date:  [Drop support for 5.3](https://github.com/zendframework/zf2/issues/7095)

**Comment by adamlundrigan** [comment]
The change isn't retroactive, so since ZfcUser and ZfcBase support ZF2 <2.4.x we also need to keep support for PHP 5.3.  I'm in favor of setting ZfcUser 2.x minimum ZF2 version at 2.4 so we can then target PHP >5.3 only

**Comment by texdc** [comment]
All it takes is a tag of the current version to move forward.  No need to put it off.

**Comment by adamlundrigan** [comment]
It's in progress. `master` is ‎what will become v2.0 once it's ready.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the Bell network.                                                                                                                                                                                                                From: George CookseySent: Wednesday, January 14, 2015 11:45 PMTo: ZF-Commons/ZfcBaseReply To: ZF-Commons/ZfcBaseCc: Adam LundriganSubject: Re: [ZfcBase] ProvidesEventsForm should extend ZfcBase\EventManager\EventProvider (#56)All it takes is a tag of the current version to move forward.  No need to put it off.

—Reply to this email directly or view it on GitHub.
