### ISSUE TITLE
Allow Custom Module Layout for ZfcUser

### ISSUE THREAD

**Issue by pascalmarcotte** [ZF-Commons/ZfcBase#61]
Sorry if this belongs in ZfcUser, but there's no "Issue" button there...

If my module X specifies a custom layout X (using EdpModuleLayouts) and I logout, ZfcUser logs me out, and redirects me to user/login, which is rendered using the Application's default layout/layout, and not layout X.

That's a problem when my layout X hides functionality from visitors, while the default Application layout reveals functionality not intended for users of my module X.

Thanks.

Pascal Marcotte

**Comment by adamlundrigan** [comment]
@Danielss89 this can be closed, not applicable to ZfcBase
