### ISSUE TITLE
AbstractDbMapper is missing setTableName

### ISSUE THREAD

**Issue by aadswebdesign** [ZF-Commons/ZfcBase#73]
Just found out that  Mapper\AbstractDbMapper is missing this.
public function setTableName($tableName){
        $this->tableName = $tableName;
        return $this;
 }
Or am I wrong?

**Comment by adamlundrigan** [comment]
Indeed.  ZfcUser's mapper [has implemented that itself](https://github.com/ZF-Commons/ZfcUser/blob/master/src/ZfcUser/Mapper/User.php#L47).  Probably should be ported from there to here?

**Comment by adamlundrigan** [comment]
After some thought I'd prefer to only allow setting the table name on construct, as I don't see the use case for changing the table name on-the-fly (https://github.com/ZF-Commons/ZfcUser/issues/552)

**Comment by Danielss89** [comment]
Agree with @adamlundrigan. It doesn't make sense to change the table on-the-fly.

**Comment by stijnhau** [comment]
any progress on this?
